[project]
name = "bittorrent-rust"
version = "0.1.0"
description = "A modern bencode parser written from scratch for the next generation of torrent streaming"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["zensical>=0.0.10"]
